FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y ffmpeg git
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir "git+https://github.com/openai/whisper.git"

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]